title: Codedhans
email: codedspace1@gmail.com
description: Art of Software.
baseurl: "" # Empty because we are at the root domain
url: "https://codedhans.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Allows future posts to be published
future: false

# Optional: Uncomment if you want GitHub Actions to build automatically
# on:
#   schedule:
#     - cron: '0 0 * * *' # Runs daily at midnight
